[package]
name = "numeric_expressions"
version = "0.1.0"
edition = "2021"
authors = ["André Carvalhais"]

[lib]
name = "parser"
path = "src/parser.rs"

[[bin]]
name = "solver"
path = "src/main.rs"

[dependencies]
