[package]
name = "desafio_05"
version = "0.1.0"
authors = ["Leo Silva Souza <leovano@protonmail.com>"]

[dependencies]
fnv = "1.0.6"
indexmap = "1.0.1"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.22"
