os:
  - linux

dist: trusty
sudo: required

notifications:
  webhooks: https://www.travisbuddy.com

matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install pylint
      script:
        - ./travis-ci/presubmit.sh dircheck pycheck validator

    - language: go
      go: master
      install:
        - go get -u golang.org/x/lint/golint
      script:
        - ./travis-ci/presubmit.sh gocheck

