os:
  - linux

dist: trusty
sudo: required

language: python
python:
  - 3.6

install:
  - pip install pylint

script:
  - ./travis-ci/presubmit.sh

notifications:
  webhooks: https://www.travisbuddy.com
  on_success: never
