os:
  - linux

dist: trusty
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip
  - sudo pip3 install --upgrade pip
  - sudo pip3 install pylint

script:
  - pushd ./travis-ci
  - ./codecheck.sh
  - popd
  - ./travis-ci/validator.sh
