#!/bin/bash
# Generated by Chat GPT

# Check if the parameter is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <username:branch-name>"
    exit 1
fi

# Split the input into username and branch-name
IFS=':' read -r USERNAME BRANCH_NAME <<< "$1"

# Default to master if no branch name is provided
if [ -z "$BRANCH_NAME" ]; then
    BRANCH_NAME="master"
fi

# Repository name
REPOSITORY_NAME="op-desafios"

# Add remote for the given username
git remote add $USERNAME https://github.com/$USERNAME/$REPOSITORY_NAME

# Fetch the latest changes from this new remote
git fetch $USERNAME

# Checkout a new branch based on the fork's branch
git checkout -b ${USERNAME}-$BRANCH_NAME --track $USERNAME/$BRANCH_NAME

