env:
  browser: true
  es2021: true
  node: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "space-before-function-paren": ["error", {
    "anonymous": "always",
    "asyncArrow": "always",
    "named": "never"
  }]
}
