all:
	cc main.c -Wall -g -ljson-c -o ../bin/runme.elf
	echo "localizado em ../bin/runme.elf"
build:
	echo "Assim o Software precisa acompanhar suas licenças"
	cc main.c -static -ljson-c -o ../bin/runme.elf
clean:
	rm ../bin/*
